// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-woGybSCuMon5hkJy1jHAWWCcfrgc0EM',
    appId: '1:445437568272:web:8f15cb780ff9981dcff195',
    messagingSenderId: '445437568272',
    projectId: 'ola-programador',
    authDomain: 'ola-programador.firebaseapp.com',
    storageBucket: 'ola-programador.appspot.com',
    measurementId: 'G-GBYMYRNJLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsBU09Mp3ezy45EV-D5ra81E-4ohIQpDE',
    appId: '1:445437568272:android:1844e03b4be42554cff195',
    messagingSenderId: '445437568272',
    projectId: 'ola-programador',
    storageBucket: 'ola-programador.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUB33JMU_Yi2njH51faSQpvLFUJVLxmMk',
    appId: '1:445437568272:ios:8f40bb000fc5352ccff195',
    messagingSenderId: '445437568272',
    projectId: 'ola-programador',
    storageBucket: 'ola-programador.appspot.com',
    iosBundleId: 'com.example.meuPrimeiroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUB33JMU_Yi2njH51faSQpvLFUJVLxmMk',
    appId: '1:445437568272:ios:3bb747212b1a3230cff195',
    messagingSenderId: '445437568272',
    projectId: 'ola-programador',
    storageBucket: 'ola-programador.appspot.com',
    iosBundleId: 'com.example.meuPrimeiroApp.RunnerTests',
  );
}
